<?php

namespace AppBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    /***
     * Columns needed to manage in the controller for contacts
     * @var array
     */
    public static $columns = ['firstName', 'lastName', 'birthDate', 'street', 'number', 'zip', 'city', 'country'];

}
