<?php

namespace AppBundle\Repository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository
{
    /***
     * Email types accepted
     * @var array
     */
    public static $emailTypes = ['Home', 'Work', 'other'];

    /***
     * Columns needed to manage in the controller for phones
     * @var array
     */
    public static $columns = ['type', 'email'];
}
